# Work-specific macOS tasks
---
- name: Check if running in a virtual environment
  command: sysctl -n machdep.cpu.brand_string
  register: cpu_brand
  changed_when: false

- name: Set fact for virtualization status
  set_fact:
    is_virtual: "{{ cpu_brand.stdout.endswith('(Virtual)') }}"

- name: Display virtualization status
  debug:
    msg: "This system is {{ 'virtual' if is_virtual else 'physical' }}"

- name: Install work-specific Homebrew packages
  homebrew:
    name: "{{ work_homebrew_packages | difference(vm_incompatible_packages) if is_virtual else work_homebrew_packages }}"
    state: present
    force_formula: true

- name: Install work-specific Homebrew casks
  homebrew_cask:
    name: "{{ work_homebrew_casks | difference(vm_incompatible_casks) if is_virtual else work_homebrew_casks }}"
    state: present
    accept_external_apps: true
    install_options: 'no-quarantine'
    sudo_password: "{{ sudo_pass }}"
