# Work-specific macOS tasks
---
- name: Install work-specific Homebrew packages
  homebrew:
    name: "{{ work_homebrew_packages }}"
    state: present

- name: Install work-specific Homebrew casks
  homebrew_cask:
    name: "{{ work_homebrew_casks }}"
    state: present
    accept_external_apps: true
