---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Deploy chezmoi SSH key
  ansible.builtin.copy:
    src: chezmoi_id_ed25519
    dest: "{{ ansible_env.HOME }}/.ssh/chezmoi_id_ed25519"
    mode: '0600'

- name: Deploy chezmoi SSH public key
  ansible.builtin.copy:
    src: chezmoi_id_ed25519.pub
    dest: "{{ ansible_env.HOME }}/.ssh/chezmoi_id_ed25519.pub"
    mode: '0644'

- name: Create SSH config for GitHub
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    create: yes
    mode: '0600'
    block: |
      Host github.com
        IdentityFile ~/.ssh/chezmoi_id_ed25519
        User git

- name: Initialize chezmoi repository from repo
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ chezmoi_repo }}
  args:
    creates: ~/.local/share/chezmoi
