---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Deploy chezmoi SSH key
  ansible.builtin.copy:
    src: chezmoi_id_ed25519
    dest: "{{ ansible_env.HOME }}/.ssh/chezmoi_id_ed25519"
    mode: '0600'

- name: Initialize chezmoi repository from repo
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ chezmoi_repo }}
  args:
    creates: ~/.local/share/chezmoi
