# Common macOS laptop tasks
---
- name: Check if running in a virtual environment
  command: sysctl -n machdep.cpu.brand_string
  register: cpu_brand
  changed_when: false

- name: Set fact for virtualization status
  set_fact:
    is_virtual: "{{ cpu_brand.stdout.endswith('(Virtual)') }}"

- name: Display virtualization status
  debug:
    msg: "This system is {{ 'virtual' if is_virtual else 'physical' }}"

- name: Update Homebrew
  homebrew:
    update_homebrew: true

- name: Install common Homebrew packages
  homebrew:
    name: "{{ common_homebrew_packages | difference(vm_incompatible_packages) if is_virtual else common_homebrew_packages }}"
    state: present
    force_formula: true

- name: Install common Homebrew casks
  homebrew_cask:
    name: "{{ common_homebrew_casks | difference(vm_incompatible_casks) if is_virtual else common_homebrew_casks }}"
    state: present
    accept_external_apps: true
    install_options: 'no-quarantine'
    sudo_password: "{{ sudo_pass }}"

- name: Automatically hide and show the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "true"

- name: Remove the auto-hiding Dock delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: "0"

- name: Remove the animation when hiding/showing the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: "0"

- name: Disable smart quotes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: "false"

- name: Disable smart dashes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: "false"

- name: Disable natural scroll for mouse and trackpad
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: "false"
    state: present

- name: Set keyboard repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: "2"

- name: Set delay until repeat (in milliseconds)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: "10"
