---
- hosts: home_laptops
  vars_prompt:
    - name: sudo_pass
      prompt: "Enter sudo password for cask"
      private: yes

  roles:
    - role: laptop_common
    - role: home_laptop
    - role: chezmoi

  pre_tasks:
    - name: Debug common_homebrew_packages variable
      debug:
        var: common_homebrew_packages

  tasks:
    - name: Verify home-specific configurations
      debug:
        msg: "Configuring home laptop for {{ ansible_user_id }}"
