---
- hosts: work_laptops
  vars_prompt:
    - name: sudo_pass
      prompt: "Enter sudo password for cask"
      private: yes

  roles:
    - role: laptop_common
    - role: work_laptop
    - role: chezmoi

  tasks:
    - name: Verify work-specific configurations
      debug:
        msg: "Configuring work laptop for {{ ansible_user_id }}"
