---
- hosts: work_laptops
  roles:
    - role: laptop_common
    - role: work_laptop

  tasks:
    - name: Verify work-specific configurations
      debug:
        msg: "Configuring work laptop for {{ ansible_user_id }}"
